#!/bin/ash

# Get the Minecraft Server binary
# TODO this URL needs research, I do not currently know how the GUID is generated by Mojang and how regularly it changes.
# Potentially we could look at page scraping for this URL to make it dynamic.
# THE most important thing is that the server binary is NOT shipped in the Docker image and is fetched by the end user due to licensing.
wget https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar

# Run the jar in a JVM.. this will fail on the first run due to licensing which is normal.
# It will however create the base set of server files.
java -jar server.jar

# Auto accept the EULA - changes value from false to true.
sed -i 's/false/true/g' eula.txt

# Finally run the server.
# TODO xms and xmx should be set here to provide JVM memory limits.
java -jar server.jar